#The max number of threads that the plugin can use.
maxThreads: 1

debug: false

autobackup:
  enabled: true
  #the type of backup to use. Valid values are: MINUTES, HOURS, SECONDS
  type: HOURS
  #interval
  interval: 2
  #number of backups files to keep
  keep: 15