name: Backpacks
version: '${project.version}'
main: br.com.backpacks.Main
api-version: '1.20'

commands:
  bpdebug:
    description: 'Just to make easy debugging'
    aliases:
      - 'bbug'
  bpgive:
    description: 'Give a backpack to a player'
    aliases:
      - 'bpgive'
    usage: '/backpackgive <player> <backpackType>'
  bplist:
    description: 'Show all backpacks'
    aliases:
      - 'bplist'
    usage: '/backpacklist'
  bpgiveid:
    description: 'Give a existent backpack to a player'
    aliases:
      - 'bpgiveid'
    usage: '/backpackgiveid <player> <backpackId>'
  bpbackup:
    description: 'Make a new backup file'
    aliases:
      - 'bpbackup'
    usage: '/backpacksbackup <create|remove|rollback> <backupName>'
  bpreload:
    description: 'Reload the config file'
    aliases:
      - 'bpreload'
      - 'bprl'
    usage: '/reload'