name: Backpacks
version: '${project.version}'
main: br.com.backpacks.Main
api-version: '1.20'

commands:
  bdebug:
    description: 'Just to make easy debugging'
    aliases:
      - 'bbug'
  backpackgive:
    description: 'Give a backpack to a player'
    aliases:
      - 'bpgive'
    usage: '/backpackgive <player> <backpackType>'
  backpacklist:
    description: 'show all backpacks'
    aliases:
      - 'bplist'
    usage: '/backpacklist'
  backpackgiveid:
    description: 'Give a existent backpack to a player'
    aliases:
      - 'bpgiveid'
    usage: '/backpackgiveid <player> <backpackId>'
  backup:
    description: 'Make a new backup file'
    aliases:
      - 'bpbackup'
    usage: '/backup <create/remove>'