name: Backpacks
version: '1.0'
main: br.com.backpacks.Main
api-version: '1.20'

depend:
  - ProtocolLib

commands:
  bpgive:
    description: 'Give a backpack to a player'
    aliases:
      - 'bpgive'
    usage: '/backpackgive <player> <backpackType>'
  bplist:
    description: 'Show all backpacks'
    aliases:
      - 'bplist'
    usage: '/backpacklist'
  bpbackup:
    description: 'Make a new backup file'
    aliases:
      - 'bpbackup'
    usage: '/backpacksbackup <create|remove|rollback> <backupName>'
  bpreload:
    description: 'Reload the config file'
    aliases:
      - 'bpreload'
      - 'bprl'
    usage: '/bpreload'
  bpupgbackpack:
    description: 'Upgrade the holding backpack'
    aliases:
      - 'bpupgbp'
    usage: '/bpupgbackpack'
  bpupgive:
    description: 'Give a new Backpack Upgrade to a player'
    usage: '/bpupgive <upgradeType> <player>'